---
application:
  name: "youtube-to-bitchute-api"
  project: "bitchute-uploader"
  organization: "QoveryCommunity"
routers:
- name: "main-youtube-to-bitchute-api"
  routes:
  - application_name: "youtube-to-bitchute-api"
    paths:
    - "/*"
